[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$RciZk7JWqjXm3Pt/7z2HsA$bMH7lNOZcaf4N0dh5XCNGGDXzUemimLRo02H4E0fN6KZ6pbBn.mZjd7w9yUxkk.SL5JDIHjNBtF5TjXtCcMzVg
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
dev_mode = all

